/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * NetPilot API
 * NetPilot API Documentation
 * OpenAPI spec version: 1.0
 */
/**
 * User role
 */
export type UserDtoRole = (typeof UserDtoRole)[keyof typeof UserDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoRole = {
  ADMINISTRATOR: "ADMINISTRATOR",
  TEACHER: "TEACHER",
  STUDENT: "STUDENT",
} as const;

export interface UserDto {
  /** User ID */
  id: number;
  /** User email */
  email: string;
  /** Username */
  username: string;
  /** Provider ID */
  providerId: string;
  /** User role */
  role: UserDtoRole;
  /** Creation date */
  createdAt: string;
  /** Last update date */
  updatedAt: string;
}

export interface AuthResponseDto {
  /** Authentication status */
  isAuthenticated: boolean;
  /** Authenticated user */
  user?: UserDto;
}

export interface LogoutResponseDto {
  /** Logout message */
  message: string;
}

export interface ErrorResponseDto {
  /** Error message */
  error: string;
}

export interface RuleScheduleDto {
  /** When the rule will be reverted */
  scheduledFor: string;
}

/**
 * Rule action (pass/block/reject)
 */
export type FirewallRuleDtoAction =
  (typeof FirewallRuleDtoAction)[keyof typeof FirewallRuleDtoAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FirewallRuleDtoAction = {
  pass: "pass",
  block: "block",
  reject: "reject",
} as const;

/**
 * Rule direction (in/out)
 */
export type FirewallRuleDtoDirection =
  (typeof FirewallRuleDtoDirection)[keyof typeof FirewallRuleDtoDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FirewallRuleDtoDirection = {
  in: "in",
  out: "out",
} as const;

/**
 * IP protocol version (inet=IPv4, inet6=IPv6, inet46=IPv4+IPv6)
 */
export type FirewallRuleDtoIpprotocol =
  (typeof FirewallRuleDtoIpprotocol)[keyof typeof FirewallRuleDtoIpprotocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FirewallRuleDtoIpprotocol = {
  inet: "inet",
  inet6: "inet6",
  inet46: "inet46",
} as const;

/**
 * Active schedule for this rule
 * @nullable
 */
export type FirewallRuleDtoSchedule = RuleScheduleDto | null;

export interface FirewallRuleDto {
  /** Unique identifier for the rule */
  uuid: string;
  /** Whether the rule is enabled */
  enabled: string;
  /** Rule action (pass/block/reject) */
  action: FirewallRuleDtoAction;
  /** Rule direction (in/out) */
  direction: FirewallRuleDtoDirection;
  /** IP protocol version (inet=IPv4, inet6=IPv6, inet46=IPv4+IPv6) */
  ipprotocol: FirewallRuleDtoIpprotocol;
  /** Interface name */
  interface?: string;
  /** Protocol type */
  protocol?: string;
  /** Source network/address */
  source_net?: string;
  /** Source port */
  source_port?: string;
  /** Destination network/address */
  destination_net?: string;
  /** Destination port */
  destination_port?: string;
  /** Rule description */
  description?: string;
  /** Whether logging is enabled */
  log: string;
  /** State type (keep state, sloppy state, etc.) */
  statetype?: string;
  /** State policy (default, if-bound, floating) */
  state_policy?: string;
  /** Quick rule (process immediately) */
  quick?: boolean;
  /** Gateway for this rule */
  gateway?: string;
  /** Sequence number */
  sequence?: string;
  /** Categories assigned to this rule */
  categories?: string[];
  /**
   * Active schedule for this rule
   * @nullable
   */
  schedule?: FirewallRuleDtoSchedule;
}

export interface FirewallRulesResponseDto {
  /** Total number of rules */
  total: number;
  /** List of firewall rules */
  rules: FirewallRuleDto[];
}

export interface ScheduleRuleChangeDto {
  /** UUID of the firewall rule */
  ruleUuid: string;
  /** Time when the rule should be reverted back (HH:mm format) */
  revertAt: string;
}

export interface ScheduledRuleChangeResponseDto {
  /** ID of the scheduled change */
  id: number;
  /** UUID of the firewall rule */
  ruleUuid: string;
  /** Action that will be performed (this reverts the immediate change) */
  action: string;
  /** When the rule will be reverted */
  scheduledFor: string;
  /** Whether the revert has been executed */
  executed: boolean;
  /** When the revert was executed */
  executedAt?: string;
}

export interface PaginatedUsersResponseDto {
  users: UserDto[];
  /** Total number of users */
  total: number;
  /** Current page number */
  page: number;
  /** Total number of pages */
  totalPages: number;
}

/**
 * New role for the user
 */
export type UserRoleEditDtoRole =
  (typeof UserRoleEditDtoRole)[keyof typeof UserRoleEditDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRoleEditDtoRole = {
  ADMINISTRATOR: "ADMINISTRATOR",
  TEACHER: "TEACHER",
  STUDENT: "STUDENT",
} as const;

export interface UserRoleEditDto {
  /** New role for the user */
  role: UserRoleEditDtoRole;
}

export type FirewallControllerToggleFirewallRuleParams = {
  /**
   * Unique identifier of the firewall rule to toggle
   */
  uuid: string;
};

export type AdminControllerGetAllUsersParams = {
  /**
   * Page number
   */
  page: number;
};
