/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * NetPilot API
 * NetPilot API Documentation
 * OpenAPI spec version: 1.0
 */
export interface UserDto {
  /** User ID */
  id: number;
  /** User email */
  email: string;
  /** Username */
  username: string;
  /** Provider ID */
  providerId: string;
  /** Creation date */
  createdAt: string;
  /** Last update date */
  updatedAt: string;
}

export interface AuthResponseDto {
  /** Authentication status */
  isAuthenticated: boolean;
  /** Authenticated user */
  user?: UserDto;
}

export interface LogoutResponseDto {
  /** Logout message */
  message: string;
}

export interface ErrorResponseDto {
  /** Error message */
  error: string;
}

export interface UserResponseErrorDto {
  /** Error message */
  message: string;
  /** Error message */
  error: string;
  /** HTTP status code */
  statusCode: number;
}
