/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * NetPilot API
 * NetPilot API Documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminControllerGetAllUsersParams,
  PaginatedUsersResponseDto,
  UserRoleEditDto,
} from "../openapi.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get all users with pagination
 */
export const adminControllerGetAllUsers = (
  params: AdminControllerGetAllUsersParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PaginatedUsersResponseDto>(
    {
      url: `http://localhost:4000/api/v1/admin/users`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getAdminControllerGetAllUsersQueryKey = (
  params?: AdminControllerGetAllUsersParams,
) => {
  return [
    `http://localhost:4000/api/v1/admin/users`,
    ...(params ? [params] : []),
  ] as const;
};

export const getAdminControllerGetAllUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
  TError = unknown,
>(
  params: AdminControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminControllerGetAllUsersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminControllerGetAllUsers>>
  > = ({ signal }) =>
    adminControllerGetAllUsers(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminControllerGetAllUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerGetAllUsers>>
>;
export type AdminControllerGetAllUsersQueryError = unknown;

export function useAdminControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
  TError = unknown,
>(
  params: AdminControllerGetAllUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetAllUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
  TError = unknown,
>(
  params: AdminControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetAllUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
  TError = unknown,
>(
  params: AdminControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all users with pagination
 */

export function useAdminControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
  TError = unknown,
>(
  params: AdminControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof adminControllerGetAllUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAdminControllerGetAllUsersQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Edit a user role
 */
export const adminControllerEditUserRole = (
  id: number,
  userRoleEditDto: UserRoleEditDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `http://localhost:4000/api/v1/admin/user/role/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: userRoleEditDto,
    },
    options,
  );
};

export const getAdminControllerEditUserRoleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminControllerEditUserRole>>,
    TError,
    { id: number; data: UserRoleEditDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminControllerEditUserRole>>,
  TError,
  { id: number; data: UserRoleEditDto },
  TContext
> => {
  const mutationKey = ["adminControllerEditUserRole"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminControllerEditUserRole>>,
    { id: number; data: UserRoleEditDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return adminControllerEditUserRole(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminControllerEditUserRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminControllerEditUserRole>>
>;
export type AdminControllerEditUserRoleMutationBody = UserRoleEditDto;
export type AdminControllerEditUserRoleMutationError = unknown;

/**
 * @summary Edit a user role
 */
export const useAdminControllerEditUserRole = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminControllerEditUserRole>>,
      TError,
      { id: number; data: UserRoleEditDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminControllerEditUserRole>>,
  TError,
  { id: number; data: UserRoleEditDto },
  TContext
> => {
  const mutationOptions =
    getAdminControllerEditUserRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
