/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * NetPilot API
 * NetPilot API Documentation
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ActiveSessionsAnalyticsDto,
  DashboardStatisticsDto,
} from "../openapi.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves statistics for users and firewall rules
 * @summary Get dashboard statistics
 */
export const analyticsControllerGetStatistics = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardStatisticsDto>(
    {
      url: `http://localhost:4000/api/v1/analytics/statistics`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getAnalyticsControllerGetStatisticsQueryKey = () => {
  return [`http://localhost:4000/api/v1/analytics/statistics`] as const;
};

export const getAnalyticsControllerGetStatisticsQueryOptions = <
  TData = Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAnalyticsControllerGetStatisticsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof analyticsControllerGetStatistics>>
  > = ({ signal }) => analyticsControllerGetStatistics(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnalyticsControllerGetStatisticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof analyticsControllerGetStatistics>>
>;
export type AnalyticsControllerGetStatisticsQueryError = unknown;

export function useAnalyticsControllerGetStatistics<
  TData = Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
          TError,
          Awaited<ReturnType<typeof analyticsControllerGetStatistics>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnalyticsControllerGetStatistics<
  TData = Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
          TError,
          Awaited<ReturnType<typeof analyticsControllerGetStatistics>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnalyticsControllerGetStatistics<
  TData = Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get dashboard statistics
 */

export function useAnalyticsControllerGetStatistics<
  TData = Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof analyticsControllerGetStatistics>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAnalyticsControllerGetStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieves time series data of active user sessions throughout the current day
 * @summary Get active sessions analytics
 */
export const analyticsControllerGetActiveSessionsAnalytics = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ActiveSessionsAnalyticsDto>(
    {
      url: `http://localhost:4000/api/v1/analytics/active-sessions`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getAnalyticsControllerGetActiveSessionsAnalyticsQueryKey = () => {
  return [`http://localhost:4000/api/v1/analytics/active-sessions`] as const;
};

export const getAnalyticsControllerGetActiveSessionsAnalyticsQueryOptions = <
  TData = Awaited<
    ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAnalyticsControllerGetActiveSessionsAnalyticsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>>
  > = ({ signal }) =>
    analyticsControllerGetActiveSessionsAnalytics(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AnalyticsControllerGetActiveSessionsAnalyticsQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>>
  >;
export type AnalyticsControllerGetActiveSessionsAnalyticsQueryError = unknown;

export function useAnalyticsControllerGetActiveSessionsAnalytics<
  TData = Awaited<
    ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
  >,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
          >,
          TError,
          Awaited<
            ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnalyticsControllerGetActiveSessionsAnalytics<
  TData = Awaited<
    ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
          >,
          TError,
          Awaited<
            ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAnalyticsControllerGetActiveSessionsAnalytics<
  TData = Awaited<
    ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get active sessions analytics
 */

export function useAnalyticsControllerGetActiveSessionsAnalytics<
  TData = Awaited<
    ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof analyticsControllerGetActiveSessionsAnalytics>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getAnalyticsControllerGetActiveSessionsAnalyticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
