/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NetPilot API
 * NetPilot API Documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BulkScheduleRulesDto,
  BulkToggleRulesDto,
  FirewallControllerToggleFirewallRuleParams,
  FirewallRulesResponseDto,
  ScheduleRuleChangeDto,
  ScheduledRuleChangeResponseDto,
} from "../openapi.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves all firewall rules from OPNsense with optional interface filtering and pagination
 * @summary Get all firewall rules
 */
export const firewallControllerGetAllFirewallRules = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<FirewallRulesResponseDto>(
    { url: `/api/v1/firewall/rules`, method: "GET", signal },
    options,
  );
};

export const getFirewallControllerGetAllFirewallRulesQueryKey = () => {
  return [`/api/v1/firewall/rules`] as const;
};

export const getFirewallControllerGetAllFirewallRulesQueryOptions = <
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFirewallControllerGetAllFirewallRulesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
  > = ({ signal }) =>
    firewallControllerGetAllFirewallRules(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FirewallControllerGetAllFirewallRulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
>;
export type FirewallControllerGetAllFirewallRulesQueryError = unknown;

export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all firewall rules
 */

export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getFirewallControllerGetAllFirewallRulesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Enables or disables a firewall rule by its UUID
 * @summary Toggle a firewall rule
 */
export const firewallControllerToggleFirewallRule = (
  params: FirewallControllerToggleFirewallRuleParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v1/firewall/toggle-rule`, method: "POST", params, signal },
    options,
  );
};

export const getFirewallControllerToggleFirewallRuleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
    TError,
    { params: FirewallControllerToggleFirewallRuleParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
  TError,
  { params: FirewallControllerToggleFirewallRuleParams },
  TContext
> => {
  const mutationKey = ["firewallControllerToggleFirewallRule"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
    { params: FirewallControllerToggleFirewallRuleParams }
  > = (props) => {
    const { params } = props ?? {};

    return firewallControllerToggleFirewallRule(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FirewallControllerToggleFirewallRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>
>;

export type FirewallControllerToggleFirewallRuleMutationError = unknown;

/**
 * @summary Toggle a firewall rule
 */
export const useFirewallControllerToggleFirewallRule = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
      TError,
      { params: FirewallControllerToggleFirewallRuleParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
  TError,
  { params: FirewallControllerToggleFirewallRuleParams },
  TContext
> => {
  const mutationOptions =
    getFirewallControllerToggleFirewallRuleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Immediately enables or disables a firewall rule, and automatically reverts it at the specified time
 * @summary Toggle a firewall rule temporarily
 */
export const firewallControllerScheduleRuleChange = (
  scheduleRuleChangeDto: ScheduleRuleChangeDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ScheduledRuleChangeResponseDto>(
    {
      url: `/api/v1/firewall/schedule-rule-change`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: scheduleRuleChangeDto,
      signal,
    },
    options,
  );
};

export const getFirewallControllerScheduleRuleChangeMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof firewallControllerScheduleRuleChange>>,
    TError,
    { data: ScheduleRuleChangeDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof firewallControllerScheduleRuleChange>>,
  TError,
  { data: ScheduleRuleChangeDto },
  TContext
> => {
  const mutationKey = ["firewallControllerScheduleRuleChange"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof firewallControllerScheduleRuleChange>>,
    { data: ScheduleRuleChangeDto }
  > = (props) => {
    const { data } = props ?? {};

    return firewallControllerScheduleRuleChange(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FirewallControllerScheduleRuleChangeMutationResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerScheduleRuleChange>>
>;
export type FirewallControllerScheduleRuleChangeMutationBody =
  ScheduleRuleChangeDto;
export type FirewallControllerScheduleRuleChangeMutationError = unknown;

/**
 * @summary Toggle a firewall rule temporarily
 */
export const useFirewallControllerScheduleRuleChange = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof firewallControllerScheduleRuleChange>>,
      TError,
      { data: ScheduleRuleChangeDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof firewallControllerScheduleRuleChange>>,
  TError,
  { data: ScheduleRuleChangeDto },
  TContext
> => {
  const mutationOptions =
    getFirewallControllerScheduleRuleChangeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Enables or disables multiple firewall rules by their UUIDs
 * @summary Toggle multiple firewall rules
 */
export const firewallControllerBulkToggleRules = (
  bulkToggleRulesDto: BulkToggleRulesDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/v1/firewall/bulk-toggle`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bulkToggleRulesDto,
      signal,
    },
    options,
  );
};

export const getFirewallControllerBulkToggleRulesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof firewallControllerBulkToggleRules>>,
    TError,
    { data: BulkToggleRulesDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof firewallControllerBulkToggleRules>>,
  TError,
  { data: BulkToggleRulesDto },
  TContext
> => {
  const mutationKey = ["firewallControllerBulkToggleRules"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof firewallControllerBulkToggleRules>>,
    { data: BulkToggleRulesDto }
  > = (props) => {
    const { data } = props ?? {};

    return firewallControllerBulkToggleRules(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FirewallControllerBulkToggleRulesMutationResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerBulkToggleRules>>
>;
export type FirewallControllerBulkToggleRulesMutationBody = BulkToggleRulesDto;
export type FirewallControllerBulkToggleRulesMutationError = unknown;

/**
 * @summary Toggle multiple firewall rules
 */
export const useFirewallControllerBulkToggleRules = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof firewallControllerBulkToggleRules>>,
      TError,
      { data: BulkToggleRulesDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof firewallControllerBulkToggleRules>>,
  TError,
  { data: BulkToggleRulesDto },
  TContext
> => {
  const mutationOptions =
    getFirewallControllerBulkToggleRulesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Immediately toggles multiple firewall rules and schedules them to revert at a specific time
 * @summary Schedule multiple firewall rules to change
 */
export const firewallControllerBulkScheduleRuleChanges = (
  bulkScheduleRulesDto: BulkScheduleRulesDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/v1/firewall/bulk-schedule`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bulkScheduleRulesDto,
      signal,
    },
    options,
  );
};

export const getFirewallControllerBulkScheduleRuleChangesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof firewallControllerBulkScheduleRuleChanges>>,
    TError,
    { data: BulkScheduleRulesDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof firewallControllerBulkScheduleRuleChanges>>,
  TError,
  { data: BulkScheduleRulesDto },
  TContext
> => {
  const mutationKey = ["firewallControllerBulkScheduleRuleChanges"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof firewallControllerBulkScheduleRuleChanges>>,
    { data: BulkScheduleRulesDto }
  > = (props) => {
    const { data } = props ?? {};

    return firewallControllerBulkScheduleRuleChanges(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FirewallControllerBulkScheduleRuleChangesMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof firewallControllerBulkScheduleRuleChanges>>
  >;
export type FirewallControllerBulkScheduleRuleChangesMutationBody =
  BulkScheduleRulesDto;
export type FirewallControllerBulkScheduleRuleChangesMutationError = unknown;

/**
 * @summary Schedule multiple firewall rules to change
 */
export const useFirewallControllerBulkScheduleRuleChanges = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof firewallControllerBulkScheduleRuleChanges>>,
      TError,
      { data: BulkScheduleRulesDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof firewallControllerBulkScheduleRuleChanges>>,
  TError,
  { data: BulkScheduleRulesDto },
  TContext
> => {
  const mutationOptions =
    getFirewallControllerBulkScheduleRuleChangesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Server-Sent Events stream for real-time rule updates
 * @summary Subscribe to firewall rule change events
 */
export const firewallControllerRuleEvents = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v1/firewall/events`, method: "GET", signal },
    options,
  );
};

export const getFirewallControllerRuleEventsQueryKey = () => {
  return [`/api/v1/firewall/events`] as const;
};

export const getFirewallControllerRuleEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFirewallControllerRuleEventsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof firewallControllerRuleEvents>>
  > = ({ signal }) => firewallControllerRuleEvents(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FirewallControllerRuleEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerRuleEvents>>
>;
export type FirewallControllerRuleEventsQueryError = unknown;

export function useFirewallControllerRuleEvents<
  TData = Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerRuleEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerRuleEvents<
  TData = Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerRuleEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerRuleEvents<
  TData = Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Subscribe to firewall rule change events
 */

export function useFirewallControllerRuleEvents<
  TData = Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerRuleEvents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFirewallControllerRuleEventsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
