/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * NetPilot API
 * NetPilot API Documentation
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  FirewallControllerGetAllFirewallRulesParams,
  FirewallRulesResponseDto,
} from "../openapi.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves all firewall rules from OPNsense with optional interface filtering
 * @summary Get all firewall rules
 */
export const firewallControllerGetAllFirewallRules = (
  params?: FirewallControllerGetAllFirewallRulesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<FirewallRulesResponseDto>(
    {
      url: `http://localhost:4000/api/v1/firewall/rules`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getFirewallControllerGetAllFirewallRulesQueryKey = (
  params?: FirewallControllerGetAllFirewallRulesParams,
) => {
  return [
    `http://localhost:4000/api/v1/firewall/rules`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFirewallControllerGetAllFirewallRulesQueryOptions = <
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  params?: FirewallControllerGetAllFirewallRulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFirewallControllerGetAllFirewallRulesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
  > = ({ signal }) =>
    firewallControllerGetAllFirewallRules(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FirewallControllerGetAllFirewallRulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
>;
export type FirewallControllerGetAllFirewallRulesQueryError = unknown;

export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  params: undefined | FirewallControllerGetAllFirewallRulesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  params?: FirewallControllerGetAllFirewallRulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  params?: FirewallControllerGetAllFirewallRulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all firewall rules
 */

export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  params?: FirewallControllerGetAllFirewallRulesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFirewallControllerGetAllFirewallRulesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
