/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * NetPilot API
 * NetPilot API Documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  FirewallControllerToggleFirewallRuleParams,
  FirewallRulesResponseDto,
} from "../openapi.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves all firewall rules from OPNsense with optional interface filtering and pagination
 * @summary Get all firewall rules
 */
export const firewallControllerGetAllFirewallRules = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<FirewallRulesResponseDto>(
    {
      url: `http://localhost:4000/api/v1/firewall/rules`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getFirewallControllerGetAllFirewallRulesQueryKey = () => {
  return [`http://localhost:4000/api/v1/firewall/rules`] as const;
};

export const getFirewallControllerGetAllFirewallRulesQueryOptions = <
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFirewallControllerGetAllFirewallRulesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
  > = ({ signal }) =>
    firewallControllerGetAllFirewallRules(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FirewallControllerGetAllFirewallRulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
>;
export type FirewallControllerGetAllFirewallRulesQueryError = unknown;

export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
          TError,
          Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all firewall rules
 */

export function useFirewallControllerGetAllFirewallRules<
  TData = Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof firewallControllerGetAllFirewallRules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getFirewallControllerGetAllFirewallRulesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Enables or disables a firewall rule by its UUID
 * @summary Toggle a firewall rule
 */
export const firewallControllerToggleFirewallRule = (
  params: FirewallControllerToggleFirewallRuleParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `http://localhost:4000/api/v1/firewall/toggle-rule`,
      method: "POST",
      params,
      signal,
    },
    options,
  );
};

export const getFirewallControllerToggleFirewallRuleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
    TError,
    { params: FirewallControllerToggleFirewallRuleParams },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
  TError,
  { params: FirewallControllerToggleFirewallRuleParams },
  TContext
> => {
  const mutationKey = ["firewallControllerToggleFirewallRule"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
    { params: FirewallControllerToggleFirewallRuleParams }
  > = (props) => {
    const { params } = props ?? {};

    return firewallControllerToggleFirewallRule(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FirewallControllerToggleFirewallRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>
>;

export type FirewallControllerToggleFirewallRuleMutationError = unknown;

/**
 * @summary Toggle a firewall rule
 */
export const useFirewallControllerToggleFirewallRule = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
      TError,
      { params: FirewallControllerToggleFirewallRuleParams },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof firewallControllerToggleFirewallRule>>,
  TError,
  { params: FirewallControllerToggleFirewallRuleParams },
  TContext
> => {
  const mutationOptions =
    getFirewallControllerToggleFirewallRuleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
